---
# Install required software for compiling git from source
#
- name: Install required tools for compiling kadNode
  package:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  with_items:
    - cmake
    - wget
    - openssl 
    - mbedtls-dev
    - libmbedtls-dev
# 
# wget -cqO- http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/m/mbedtls-2.6.0-1.el7.x86_64.rpm | sudo rpm -i
# sudo rpm -i http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/m/mbedtls-2.6.0-1.el7.x86_64.rpm
  tags: [kadNode, install]


- name: Create kadNode Folder
  file: 
    path: "{{ kadNode_sources_location }}"
    state: directory
    mode: 0755
    owner: vagrant
  tags: [kadNode, install]

- name: Download kadNode sources
  git:
    clone: yes
    dest: "{{ kadNode_sources_location }}/KadNode"
    repo: "{{ kadNode_git_url }}"
  tags: [kadNode, install]

- name: checkout commit kadNode sources
  command: bash -lc "git checkout {{kadNode_git_commit}}"
  args:
    chdir: "{{kadNode_sources_location}}/KadNode"
  ignore_errors: yes
  register: result
  tags: [kadNode, install]

- debug: msg="{{ result.stdout_lines }}"
- debug: msg="{{ result.stderr_lines }}"


# Compile kadNode
# It will be compiled by using different user than root.
#
- name: Compile kadNode
  command: "{{ item }}"
  args:
    chdir: "{{ kadNode_sources_location }}/KadNode"
  with_items:
    - make clean
    - make
    #- make configure
    #- "./configure --prefix={{ kadNode_install_path }}"
    #- make
  become: true
#  become_user: "{{ kadNode_build_user }}"
  tags: [kadNode, install]

# Install compiled git
# This operation must be executed as sudo user
#
- name: Install compiled kadNode
  command: make install
  args:
    chdir: "{{ kadNode_sources_location }}/KadNode"
  tags: [kadNode, install]

# Remove downloaded sources after installation
#
- name: Cleanup downloaded sources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kadNode_sources_location }}/KadNode"
    #- "{{ kadNode_sources_location }}/KadNode"
  when: "kadNode_cleanup_after_install == true"
  tags: [kadNode, install]

# Add new kadNode executables to PATH
# It will fix the issue when kadNode compiled from source can be overridden by kadNode installed with yum
#
#- name: Add kadNode executables to PATH
#  template:
#    src: kadNode.sh.j2
#    dest: /etc/profile.d/kadNode.sh
#    owner: root
#    group: root
#    mode: 0644
#  tags: [kadNode, install]


