---
# Install required software for compiling git from source
#
- name: Install required tools for compiling kadNode
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - autoconf # Dependencies: m4 perl perl-Carp perl-Data-Dumper perl-Encode perl-Exporter perl-File-Path perl-File-Temp perl-Filter perl-Getopt-Long perl-HTTP-Tiny perl-PathTools perl-Pod-Escapes perl-Pod-Perldoc perl-Pod-Simple perl-Pod-Usage perl-Scalar-List-Utils perl-Socket perl-Storable perl-Text-ParseWords perl-Time-HiRes perl-Time-Local perl-constant perl-libs perl-macros perl-parent perl-podlators perl-threads perl-threads-shared
    - libcurl-devel
    - expat-devel
    - gcc # Dependencies: cpp glibc-devel glibc-headers kernel-headers libmpc mpfr
    - gettext-devel # Dependencies: gettext-common-devel git libgnome-keyring perl perl-Carp perl-Encode perl-Error perl-Exporter perl-File-Path perl-File-Temp perl-Filter perl-Getopt-Long perl-Git perl-HTTP-Tiny perl-PathTools perl-Pod-Escapesperl-Pod-Perldoc perl-Pod-Simple perl-Pod-Usage perl-Scalar-List-Utils perl-Socket perl-Storable perl-TermReadKey perl-Text-ParseWords perl-Time-HiRes perl-Time-Local perl-constant perl-libs perl-macros perl-parent perl-podlators perl-threads perl-threads-shared
    - kernel-headers
    - perl-devel # Dependencies: gdbm-devel glibc-devel glibc-headers kernel-headers libdb-devel perl perl-Carp perl-Encode perl-Exporter perl-ExtUtils-Install  perl-ExtUtils-MakeMaker perl-ExtUtils-Manifest perl-ExtUtils-ParseXS perl-File-Path perl-File-Temp perl-Filter perl-Getopt-Long perl-HTTP-Tiny perl-PathTools perl-Pod-Escapes perl-Pod-Perldoc perl-Pod-Simple perl-Pod-Usage perl-Scalar-List-Utils perl-Socket perl-Storable perl-Test-Harness perl-Text-ParseWords perl-Time-HiRes perl-Time-Local perl-constant perl-libs perl-macros perl-parent perl-podlators perl-threads perl-threads-shared pyparsing systemtap-sdt-devel
    - zlib-devel
  tags: [kadNode, install]


- name: Create kadNode Folder
  file: 
    path: "{{ kadNode_sources_location }}"
    state: directory
    mode: 0755
    owner: vagrant
  tags: [kadNode, install]

- name: Download kadNode sources
  git:
    clone: yes
    dest: "{{ kadNode_sources_location }}/KadNode"
    repo: "https://github.com/mwarning/KadNode.git"
  tags: [kadNode, install]

# Compile kadNode
# It will be compiled by using different user than root.
#
- name: Compile git
  command: "{{ item }}"
  args:
    chdir: "{{ kadNode_sources_location }}/KadNode"
  with_items:
    - make clean
    - make configure
    - "./configure --prefix={{ kdNode_install_path }}"
    - make
  become: true
#  become_user: "{{ kadNode_build_user }}"
  tags: [kadNode, install]

# Install compiled git
# This operation must be executed as sudo user
#
- name: Install compiled git
  command: make install
  args:
    chdir: "{{ kadNode_sources_location }}/KadNode"
  tags: [kadNode, install]

# Remove downloaded sources after installation
#
- name: Cleanup downloaded sources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kadNode_sources_location }}/KadNode"
    - "{{ kadNode_sources_location }}/KadNode"
  when: "kadNode_cleanup_after_install == true"
  tags: [kadNode, install]

# Add new kadNode executables to PATH
# It will fix the issue when kadNode compiled from source can be overridden by kadNode installed with yum
#
#- name: Add kadNode executables to PATH
#  template:
#    src: kadNode.sh.j2
#    dest: /etc/profile.d/kadNode.sh
#    owner: root
#    group: root
#    mode: 0644
#  tags: [kadNode, install]


