---
#
# Seting up kadNode service
#
- hosts: all
  become: yes
  
  vars:

  pre_tasks:
  - name: run pre_tasks
    debug:
        msg: Execute command from pre_task
  - name: Install required tools for compiling kadNode
    package:
      name: "git"
      state: latest
    ignore_errors: yes

  roles:
   #  build and install git from source
   #- { role: git-install}
   
   #   install mbedtls if not existing for compiling kadNode
   #   see OS specific script
   - { role: mbedtls , mbedtls_version="2.7.0", mbedtls_file_sha1="6c8e62985c5a73318d391e1327830b3ff85f87a0" }

   # compile spezific version with kadNode_git_commit
   - { role: kadNode , kadNode_git_commit="f164bdf"}

  tasks:
  - name: run tasks
    debug:
        msg: Execute command from task

  post_tasks:
  - name: run post_tasks
    debug:
        msg: Execute command from post_task
