---
#
# Seting up kadNode service
#
- hosts: all
  become: yes
  
  vars:

  pre_tasks:
  - name: run pre_tasks
    debug:
        msg: Execute command from pre_task
  - name: Install required tools for compiling kadNode
    package:
      name: "git"
      state: latest
    ignore_errors: yes

  roles:
   #- { role: git-install}
   - { role: kadNode , kadNode_git_commit="f164bdf"}

  tasks:
  - name: run tasks
    debug:
        msg: Execute command from task

  post_tasks:
  - name: run post_tasks
    debug:
        msg: Execute command from post_task
